<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttab-proceedings [
<!-- DOCUMENT TYPE DEFINITION FOR UNITED STATES TRADEMARK TRIAL AND APPEAL BOARD (TTAB) PROCEEDINGS
Reference this DTD as PUBLIC "-//USPTO//DTD TTAB PROCEEDINGS V1.0 2004-02-13//EN"

Contact:
U.S. Patent and Trademark Office
Electronic Information Products Division
P.O. Box 1450
Alexandria, VA 22313
ipd@uspto.gov

***** START REVISION HISTORY *****
2000-09-01
1) Renamed element ttab-proceedings to ttab-proceedings enforcing all uppercase element names.
2) Changed xml encoding from "ISO-8859-1" to "UTF-8"
3) Added prolog comment with DTD identification and contact information
4) Defined initial version of V0.1 and build date of 2000-09-01.

2000-11-14
1) Added element mark-text to property group.

2000-11-15
1) Reviewed optionality requirements and made more elements optional to reflect source 
   database requirements.
2) Removed PURGE-INDICATOR element.

2001-03-21
1) Added history-text to prosecution-entry and information-text to PROCEEDING.

2002-07-1
1) Removed information-text and added status-text to proceeding-entry.
2) Added identifier to prosecution-entry.
2002-08-26
1)Added the interlocutory-attorney-name, location-code, day-in-location, charge-to-location-code, charge-to-employee-name, into proceeding-information
2)Added data-available-code into proceeding-information
2002-09-25
1)Added the int-attorney-number(employee-number) into proceeding information
2)Added identifier into party, property and address table
2004-02-13
1) Removed status-text from proceeding-entry (reference table).

2022-01-03
1) Added an optional element tma-proceeding to property group.
2) Added mandatory element proceeding-number to tma-proceeding.
3) Added mandatory element proceeding-type-code to tma-proceeding.
	Expungement: File after 3 years of registration expiration date for petitions made before or on December 27, 2023,
	other wise 10 years after  registration expiration date Re-examination: File no later than 5 years after the date of registration.

***** END REVISION HISTORY **********
-->
<!ELEMENT ttab-proceedings (version , action-key-code , transaction-date , proceeding-information)>
<!ELEMENT version (version-no , version-date)>
<!ELEMENT version-no (#PCDATA)>
<!ELEMENT version-date (#PCDATA)>
<!ELEMENT action-key-code (#PCDATA)>
<!ELEMENT transaction-date (#PCDATA)>
<!ELEMENT proceeding-information (data-available-code | proceeding-entry+)>
<!ELEMENT data-available-code (#PCDATA)>
<!ELEMENT proceeding-entry (number, type-code?, filing-date?, employee-number?, interlocutory-attorney-name?, location-code?, day-in-location?, charge-to-location-code?, charge-to-employee-name?, status-update-date?, status-code?, party-information?, prosecution-history?)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT type-code (#PCDATA)>
<!ELEMENT filing-date (#PCDATA)>
<!ELEMENT employee-number (#PCDATA)>
<!ELEMENT interlocutory-attorney-name (#PCDATA)>
<!ELEMENT location-code (#PCDATA)>
<!ELEMENT day-in-location (#PCDATA)>
<!ELEMENT charge-to-location-code (#PCDATA)>
<!ELEMENT charge-to-employee-name (#PCDATA)>
<!ELEMENT status-update-date (#PCDATA)>
<!ELEMENT status-code (#PCDATA)>
<!ELEMENT party-information (party*)>
<!ELEMENT party (identifier?, role-code?, name?, orgname?, property-information?, address-information?)>
<!ELEMENT identifier (#PCDATA)>
<!ELEMENT role-code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT orgname (#PCDATA)>
<!ELEMENT property-information (property*)>
<!ELEMENT property (identifier?, serial-number?, registration-number?, mark-text?, tma-proceeding*)>
<!ELEMENT serial-number (#PCDATA)>
<!ELEMENT registration-number (#PCDATA)>
<!ELEMENT mark-text (#PCDATA)>
<!ELEMENT tma-proceeding (proceeding-number, proceeding-type-code)>
<!ELEMENT proceeding-number (#PCDATA)>
<!ELEMENT proceeding-type-code (#PCDATA)>
<!ELEMENT address-information (proceeding-address*)>
<!ELEMENT proceeding-address (identifier?, type-code?, name?, orgname?, address-1?, city?, state?, country?, postcode?)>
<!ELEMENT address-1 (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT prosecution-history (prosecution-entry*)>
<!ELEMENT prosecution-entry (identifier?, code?, type-code?, due-date?, date?, history-text?)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT due-date (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT history-text (#PCDATA)>
]>
<ttab-proceedings>
    <version>
        <version-no>v1.0</version-no>
        <version-date>20211227</version-date>
    </version>
    <action-key-code>DA</action-key-code>
    <transaction-date>20230101</transaction-date>
    <proceeding-information>
        <proceeding-entry>
            <number>78134559</number>
            <type-code>EXA</type-code>
            <filing-date>20040725</filing-date>
            <employee-number>0</employee-number>
            <interlocutory-attorney-name>SYSTEM ADMIN</interlocutory-attorney-name>
            <location-code>M7D</location-code>
            <day-in-location>20060820</day-in-location>
            <status-update-date>20230101</status-update-date>
            <status-code>2</status-code>
            <party-information>
                <party>
                    <identifier>330965</identifier>
                    <role-code>P</role-code>
                    <name>David J Gungner</name>
                    <property-information>
                        <property>
                            <identifier>298748</identifier>
                            <serial-number>78134559</serial-number>
                            <mark-text>REMOVE A RIB, XY LESSER THAN XX</mark-text>
                        </property>
                    </property-information>
                    <address-information>
                        <proceeding-address>
                            <identifier>453765</identifier>
                            <type-code>C</type-code>
                            <name>DAVID GUNGNER</name>
                            <address-1>POST OFFICE AREA 3302</address-1>
                            <city>LOS ANGELES</city>
                            <state>CA</state>
                            <country>US</country>
                            <postcode>90408-3302</postcode>
                        </proceeding-address>
                    </address-information>
                </party>
            </party-information>
            <prosecution-history>
                <prosecution-entry>
                    <identifier>1</identifier>
                    <code>158</code>
                    <type-code>X</type-code>
                    <date>20040725</date>
                    <history-text>APPEAL TO BOARD</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>2</identifier>
                    <code>151</code>
                    <type-code>X</type-code>
                    <date>20040725</date>
                    <history-text>APPEAL ACKNOWLEDGED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>3</identifier>
                    <code>128</code>
                    <type-code>T</type-code>
                    <date>20040726</date>
                    <history-text>INSTITUTED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>4</identifier>
                    <code>157</code>
                    <type-code>X</type-code>
                    <date>20050317</date>
                    <history-text>APPEAL BRIEF</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>5</identifier>
                    <code>900</code>
                    <type-code>T</type-code>
                    <date>20050407</date>
                    <history-text>RESPONSE DUE 20 DAYS LATE BRIEF</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>6</identifier>
                    <code>157</code>
                    <type-code>X</type-code>
                    <date>20050427</date>
                    <history-text>APPEAL BRIEF</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>7</identifier>
                    <code>802</code>
                    <type-code>T</type-code>
                    <date>20051026</date>
                    <history-text>BOARD'S DECISION: DISMISSED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>8</identifier>
                    <code>185</code>
                    <type-code>X</type-code>
                    <date>20051126</date>
                    <history-text>REQUEST FOR RECONSIDERATION</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>9</identifier>
                    <code>424</code>
                    <type-code>P</type-code>
                    <date>20051129</date>
                    <history-text>RECONSIDERATION DENIED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>10</identifier>
                    <code>185</code>
                    <type-code>X</type-code>
                    <date>20051229</date>
                    <history-text>REQUEST FOR RECONSIDERATION</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>11</identifier>
                    <code>424</code>
                    <type-code>P</type-code>
                    <date>20060106</date>
                    <history-text>RECONSIDERATION DENIED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>12</identifier>
                    <code>150</code>
                    <type-code>T</type-code>
                    <date>20060117</date>
                    <history-text>UNDELIVERABLE MAIL</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>13</identifier>
                    <code>185</code>
                    <type-code>X</type-code>
                    <date>20060205</date>
                    <history-text>REQUEST FOR RECONSIDERATION</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>14</identifier>
                    <code>424</code>
                    <type-code>P</type-code>
                    <date>20060215</date>
                    <history-text>RECONSIDERATION DENIED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>15</identifier>
                    <code>150</code>
                    <type-code>T</type-code>
                    <date>20060221</date>
                    <history-text>UNDELIVERABLE MAIL</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>16</identifier>
                    <code>185</code>
                    <type-code>X</type-code>
                    <date>20060317</date>
                    <history-text>REQUEST FOR RECONSIDERATION</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>17</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20060320</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>18</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20060419</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>19</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20060519</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>20</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20060618</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>21</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20060718</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>22</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20060817</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>23</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20060916</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>24</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20060919</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>25</identifier>
                    <code>161</code>
                    <type-code>X</type-code>
                    <date>20060920</date>
                    <history-text>BOARD`S ORDER</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>26</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20060920</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>27</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20061016</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>28</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20061017</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>29</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20061115</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>30</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20061120</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>31</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20061215</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>32</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20061217</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>33</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070114</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>34</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070116</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>35</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070213</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>36</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070214</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>37</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070315</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>38</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070319</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>39</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070414</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>40</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070415</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>41</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070514</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>42</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070515</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>43</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070613</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>44</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070614</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>45</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070713</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>46</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070715</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>47</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070812</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>48</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070813</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>49</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20070910</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>50</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20070911</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>51</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20071010</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>52</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20071012</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>53</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20071109</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>54</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20071113</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>55</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20071209</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>56</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20071211</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>57</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20080108</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>58</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080108</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>59</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20080207</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>60</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080208</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>61</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20080308</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>62</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080310</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>63</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20080407</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>64</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080408</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>65</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20080507</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>66</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080508</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>67</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20080607</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>68</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080612</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>69</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080621</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>70</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080622</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>71</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20080706</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>72</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080707</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>73</identifier>
                    <code>186</code>
                    <type-code>X</type-code>
                    <date>20080805</date>
                    <history-text>REQ FOR RECNSDRATN FROM FINAL BD DCSN</history-text>
                </prosecution-entry>
                <prosecution-entry>
                    <identifier>74</identifier>
                    <code>999</code>
                    <type-code>N</type-code>
                    <date>20080807</date>
                    <history-text>TERMINATED</history-text>
                </prosecution-entry>